CREATE TABLE `product` (`pid` INT(11) NOT NULL AUTO_INCREMENT , `purchase_price_usd` DECIMAL(10,2) NULL DEFAULT NULL , `rate_eur_usd` DECIMAL(10,2) NULL DEFAULT NULL , `stock_quantity` DECIMAL(10,2) NULL DEFAULT NULL , PRIMARY KEY (`pid`)) ENGINE = InnoDB;

CREATE TABLE `product_attribute` (`id` INT(11) NOT NULL AUTO_INCREMENT , `pid` INT(11) UNSIGNED NULL DEFAULT NULL , `paid` INT(11) NULL DEFAULT NULL , `purchase_price_usd` DECIMAL(10,2) NULL DEFAULT NULL , `rate_eur_usd` DECIMAL(10,2) NULL DEFAULT NULL , `stock_quantity` INT(11) NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

ALTER TABLE `product` CHANGE `pid` `pid` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `product_attribute` ADD CONSTRAINT `product_attribute_ibfk1` FOREIGN KEY (`pid`) REFERENCES `product`(`pid`) ON DELETE RESTRICT ON UPDATE RESTRICT;